### ISSUE TITLE
Error al crear pedido de alquiler por intervalo con contrato.

### ISSUE THREAD

**Issue by qupro** [zvERP/rental-vertical#11]
Al crear un presupuesto o pedido de venta de tipo alquiler, desde la app de ventas, si el producto en la línea de venta es un servicio de alquiler por intervalo y se marca el check de contrato, da el siguiente error.

Traceback (most recent call last):
  File "/opt/odoo-zverp/odoo/addons/base/models/ir_http.py", line 242, in _dispatch
    result = request.dispatch()
  File "/opt/odoo-zverp/odoo/http.py", line 702, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-zverp/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-zverp/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-zverp/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo-zverp/odoo/http.py", line 925, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-zverp/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-zverp/addons/web/controllers/main.py", line 1324, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo-zverp/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo-zverp/odoo/api.py", line 471, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo-zverp/odoo/api.py", line 456, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo-zverp/odoo/models.py", line 6523, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo-zverp/odoo/models.py", line 6256, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo-zverp/addons/rental_contract/models/sale.py", line 27, in onchange_contract_date_start_end
    number = self._get_number_of_time_unit()
  File "/opt/odoo-zverp/addons/rental_pricelist_interval/models/sale.py", line 26, in _get_number_of_time_unit
    res = (self.end_date - self.start_date).days + 1
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo-zverp/odoo/http.py", line 658, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-zverp/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'int' object has no attribute 'days'

**Comment by pcastelovigo** [comment]
Traceback (most recent call last):
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/addons/base/models/ir_http.py", line 242, in _dispatch
    result = request.dispatch()
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/http.py", line 702, in dispatch
    result = self._call_function(**self.params)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/http.py", line 925, in __call__
    return self.method(*args, **kw)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/addons/web/controllers/main.py", line 1324, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/api.py", line 471, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/api.py", line 456, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/models.py", line 6523, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/models.py", line 6256, in _onchange_eval
    method_res = method(self)
  File "/home/pablo/Escritorio/ODOO/TRABAJO/rental_contract/models/sale.py", line 27, in onchange_contract_date_start_end
    number = self._get_number_of_time_unit()
  File "/home/pablo/Escritorio/ODOO/TRABAJO/rental_pricelist_interval/models/sale.py", line 23, in _get_number_of_time_unit
    res = super()._get_number_of_time_unit()
  File "/home/pablo/Escritorio/ODOO/TRABAJO/rental_base/models/sale.py", line 183, in _get_number_of_time_unit
    number = ((self.end_date - self.start_date).days + 1) / 30.4167
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/http.py", line 658, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/pablo/Escritorio/ODOO/odoo-zverp/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'int' object has no attribute 'days'

**Comment by pcastelovigo** [comment]
https://github.com/flinq-ingenieria/rental-vertical/commit/cfae69450503d62587cd36921ed2cca2f130af43
añadida ventana que advierte al usuario gracilmente que no se pueden vender los contratos en si mismos;
considerar:
filtro para no mostrar contratos en ventas ¿como?
ocultar el selector pedido de venta/pedido de alquiler, puesto que cada cosa debe hacerse desde su aplicacion

**Comment by pcastelovigo** [comment]
https://github.com/flinq-ingenieria/rental-vertical/pull/14
